### PR TITLE
feat: add unit and class for specific gravity trend

### PR DESCRIPTION
**Pull request by sairon**
Payload parsed by the rapt_ble integration now includes trend of the specific gravity change (documented in https://github.com/sairon/rapt-ble/commit/7bef92fc3c1439a1d2c9180411aa695883c954a3). This PR adds new unit and device class for these metrics.

### CODE REVIEW

**Comment by sairon** [comment]
@bdraco Before I added `rapt_ble` integration to the Core, `tilt_ble` was the only integration using `SPECIFIC_GRAVITY` too. But I agree that this one will likely stay unique for RAPT devices.

So what you're suggesting is to use `SensorDeviceClass` and `Units` as base classes for a library-specific enums, which will be used in my code and tests, correct?

**Comment by bdraco** [comment]
> @bdraco Before I added `rapt_ble` integration to the Core, `tilt_ble` was the only integration using `SPECIFIC_GRAVITY` too. But I agree that this one will likely stay unique for RAPT devices.
> 
> ~So what you're suggesting is to use `SensorDeviceClass` and `Units` as base classes for a library-specific enums, which will be used in my code and tests, correct?~
> 
> D'oh, just realized that subclassing enums is forbidden ([PEP 435](https://peps.python.org/pep-0435/#restricted-subclassing-of-enumerations)), so I will actually need to define own enums for the purpose of the integration. So should I go that way?

Yes, you'll have to copy the enum since enums can't be subclasses (kinda annoying... )

**Comment by sairon** [comment]
OK, could be done like this: https://github.com/sairon/rapt-ble/blob/bc626eb736cef0d16acc6803a8ea09d472a51dfa/src/rapt_ble/custom_state_data.py

Obviously mypy hasn't issues with the fact that `update_sensor` is getting `device_class` that is actually not its own `SensorDeviceClass` as specified in the type hints, but linter in PyCharm doesn't like if it's named differently, so I used the original names for custom enums. I can't really say I like this approach but if you prefer it rather then spamming `sensor_state_data` library with exotic units and classes, I can live with that.

**Comment by bdraco** [comment]
> OK, could be done like this: [sairon/rapt-ble@`bc626eb`/src/rapt_ble/custom_state_data.py](https://github.com/sairon/rapt-ble/blob/bc626eb736cef0d16acc6803a8ea09d472a51dfa/src/rapt_ble/custom_state_data.py)
> 
> Obviously mypy hasn't issues with the fact that `update_sensor` is getting `device_class` that is actually not its own `SensorDeviceClass` as specified in the type hints, but linter in PyCharm doesn't like if it's named differently, so I used the original names for custom enums. I can't really say I like this approach but if you prefer it rather then spamming `sensor_state_data` library with exotic units and classes, I can live with that.

I don't really love it either but I also don't want to keep adding to this library unless we have at least 2-3 integrations that need it to keep it from growing into something unmanageable.

**Comment by sairon** [comment]
Understood. I will add a link to this PR to the code so it's clear I wasn't crazy when I implemented it like that :) We can close it here, I will do some more tests of the new sensor and create a Core PR later. Thanks!

**Pull request closed without merging**
